// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Speed

#include "../ui.h"
#include <stdio.h>

lv_obj_t * uic_BtnDecrease;
lv_obj_t * uic_BtnIncrease;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_SpeedSpinner = NULL;
lv_obj_t * ui_SpeedUnit = NULL;
lv_obj_t * ui_SpeedValue = NULL;
lv_obj_t * ui_BtnIncrease = NULL;
lv_obj_t * ui_BtnIncreaseLabel = NULL;
lv_obj_t * ui_BtnDecrease = NULL;
lv_obj_t * ui_BtnDecreaseLabel = NULL;

uint16_t speed_value = 200;
// event funtions
void ui_event_BtnIncrease(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Increment speed value
        speed_value++;
        
        // Update the label with new value
        char speed_text[10];
        snprintf(speed_text, sizeof(speed_text), "%u", speed_value);
        lv_label_set_text(ui_SpeedValue, speed_text);
    }
}

void ui_event_BtnDecrease(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Decrement speed value
        if(speed_value > 0) {
            speed_value--;
        }
        
        // Update the label with new value
        char speed_text[10];
        snprintf(speed_text, sizeof(speed_text), "%u", speed_value);
        lv_label_set_text(ui_SpeedValue, speed_text);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_invalidate(lv_scr_act());

    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_SpeedSpinner = lv_spinner_create(ui_Screen1);
    //lv_spinner_set_anim_params(ui_SpeedSpinner, 1000, 90);
    lv_obj_set_width(ui_SpeedSpinner, 260);
    lv_obj_set_height(ui_SpeedSpinner, 230);
    lv_obj_set_x(ui_SpeedSpinner, 15);
    lv_obj_set_y(ui_SpeedSpinner, 1);
    lv_obj_set_align(ui_SpeedSpinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SpeedSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_SpeedUnit = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpeedUnit, 36);
    lv_obj_set_y(ui_SpeedUnit, 24);
    lv_obj_set_align(ui_SpeedUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedUnit, "km/h");
    lv_obj_set_style_text_color(ui_SpeedUnit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedUnit, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue, "200");
    lv_obj_set_style_text_color(ui_SpeedValue, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValue, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnIncrease = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_BtnIncrease, 40);
    lv_obj_set_height(ui_BtnIncrease, 40);
    lv_obj_set_x(ui_BtnIncrease, 0);
    lv_obj_set_y(ui_BtnIncrease, -55);
    lv_obj_set_align(ui_BtnIncrease, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnIncrease, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnIncrease, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnIncreaseLabel = lv_label_create(ui_BtnIncrease);
    lv_obj_set_width(ui_BtnIncreaseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnIncreaseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnIncreaseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnIncreaseLabel, "+");

    ui_BtnDecrease = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_BtnDecrease, 40);
    lv_obj_set_height(ui_BtnDecrease, 40);
    lv_obj_set_x(ui_BtnDecrease, 0);
    lv_obj_set_y(ui_BtnDecrease, 55);
    lv_obj_set_align(ui_BtnDecrease, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnDecrease, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnDecrease, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnDecreaseLabel = lv_label_create(ui_BtnDecrease);
    lv_obj_set_width(ui_BtnDecreaseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BtnDecreaseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BtnDecreaseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BtnDecreaseLabel, "-");

    lv_obj_add_event_cb(ui_BtnIncrease, ui_event_BtnIncrease, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnDecrease, ui_event_BtnDecrease, LV_EVENT_ALL, NULL);
    uic_BtnIncrease = ui_BtnIncrease;
    uic_BtnDecrease = ui_BtnDecrease;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_SpeedSpinner = NULL;
    ui_SpeedUnit = NULL;
    ui_SpeedValue = NULL;
    uic_BtnIncrease = NULL;
    ui_BtnIncrease = NULL;
    ui_BtnIncreaseLabel = NULL;
    uic_BtnDecrease = NULL;
    ui_BtnDecrease = NULL;
    ui_BtnDecreaseLabel = NULL;

}
