// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Speed

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_SpeedSpinner;
extern lv_obj_t * ui_SpeedUnit;
extern lv_obj_t * ui_SpeedValue;
extern void ui_event_BtnIncrease(lv_event_t * e);
extern lv_obj_t * ui_BtnIncrease;
extern lv_obj_t * ui_BtnIncreaseLabel;
extern void ui_event_BtnDecrease(lv_event_t * e);
extern lv_obj_t * ui_BtnDecrease;
extern lv_obj_t * ui_BtnDecreaseLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BtnIncrease;
extern lv_obj_t * uic_BtnDecrease;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

