// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: Speed

#include "ui.h"

void cbButtonIncrease(lv_event_t * e)
{
	// Your code here
}

void cbButonDecrease(lv_event_t * e)
{
	// Your code here
}
